### ISSUE TITLE
Bundle install blows up in arm64

### ISSUE THREAD

**Issue by luis30n** [ankane/ruby-polars#72]
Hi! First of all, thanks for creating this gem. It's incredibly handy to generate parquet files! However, I'm experiencing a blocker for using it. These are the details about the issue, let me know if you need anything else:
```
➜  ~ uname -m

arm64
➜  ruby-polars git:(master) rvm list
   ruby-2.7.2 [ arm64 ]
 * ruby-3.1.2 [ arm64 ]
   ruby-3.2.2 [ arm64 ]
=> ruby-3.2.3 [ arm64 ]
```
Running bundle install in a repository with `polars-df` gem causes the rustc process to take lots of resources on the computer and runs endlessly:
![image](https://github.com/ankane/ruby-polars/assets/36823014/53ae767d-6b9b-4dc3-9b7e-4d5f7f05eb53)

Following the installation steps at https://github.com/ankane/ruby-polars?tab=readme-ov-file#contributing causes

```
mkdir -p tmp/arm64-darwin23/polars/3.2.3
cd tmp/arm64-darwin23/polars/3.2.3
/Users/luisalvarez/.rvm/rubies/ruby-3.2.3/bin/ruby -I. ../../../../ext/polars/extconf.rb
checking for gcc... yes
checking for g++... yes
checking for /Library/Developer/CommandLineTools/usr/bin/ar... yes
cd -
cd tmp/arm64-darwin23/polars/3.2.3
/usr/bin/make
generating target/release/libpolars.dylib (release)
cargo rustc  --manifest-path ../../../../ext/polars/Cargo.toml --target-dir target --lib --profile release -- -C linker=gcc -L native=/Users/luisalvarez/.rvm/rubies/ruby-3.2.3/lib -L native=/opt/homebrew/opt/libyaml/lib -L native=/opt/homebrew/opt/libksba/lib -L native=/opt/homebrew/opt/readline/lib -L native=/opt/homebrew/opt/zlib/lib -L native=/opt/homebrew/opt/openssl@1.1/lib -C link-arg=-Wl,-undefined,dynamic_lookup -l pthread
make: cargo: No such file or directory
make: *** [target/release/libpolars.dylib] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/make]
/Users/luisalvarez/.rvm/gems/ruby-3.2.3/gems/rake-compiler-1.2.7/lib/rake/extensiontask.rb:195:in `block (2 levels) in define_compile_tasks'
/Users/luisalvarez/.rvm/gems/ruby-3.2.3/gems/rake-compiler-1.2.7/lib/rake/extensiontask.rb:194:in `block in define_compile_tasks'
/Users/luisalvarez/.rvm/gems/ruby-3.2.3/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/Users/luisalvarez/.rvm/gems/ruby-3.2.3/bin/ruby_executable_hooks:22:in `eval'
/Users/luisalvarez/.rvm/gems/ruby-3.2.3/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => compile => compile:arm64-darwin23 => compile:polars:arm64-darwin23 => copy:polars:arm64-darwin23:3.2.3 => tmp/arm64-darwin23/polars/3.2.3/polars.bundle
(See full trace by running task with --trace)
<internal:/Users/luisalvarez/.rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- polars/polars (LoadError)
```

Are you familiar with this issue? Is there anything I can do as a workaround?
Thanks for the help!

**Comment by ankane** [comment]
Hi @luis30n, it looks like the gem is installing from source, which takes a while. You probably need to add `arm64-darwin` as a platform in your `Gemfile.lock` by running:

```sh
bundle lock --add-platform arm64-darwin
```

**Comment by luis30n** [comment]
Hi @ankane 
thanks for the help, unfortunately, this did not solve the issue so we decided to do it in another way.
