### ISSUE TITLE
Error while read row of dataframe

### ISSUE THREAD

**Issue by suaron** [ankane/ruby-polars#74]
Hello!
Thanks for creating this gem.
I am play around with this gem and faced with exception while try get `row` by `id` after column type conversion.

```ruby
require "polars-df"

df = Polars::DataFrame.new([
  {startTime: "2022-02-18 13:14:41 -0400"}
])

df.row(0)

df = df.with_columns(
  Polars.col("startTime").str.to_datetime("%Y-%m-%d %H:%M:%S %z"),
)

df.row(0)
^^^^^^
fatal: called `Result::unwrap()` on an `Err` value: Error(Exception(#<Polars::Todo: Polars::Todo>))
/home/jovyan/.local/share/gem/ruby/3.3.0/gems/polars-df-0.10.0-x86_64-linux/lib/polars/data_frame.rb:4610:in `row_tuple'
/home/jovyan/.local/share/gem/ruby/3.3.0/gems/polars-df-0.10.0-x86_64-linux/lib/polars/data_frame.rb:4610:in `row'
(irb):in `<top (required)>'
```

but `df[0]` return successfully row after column type conversion

```
ruby --version
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]

gem list | grep polars
polars-df (0.10.0 x86_64-linux)
```

**Comment by ankane** [comment]
Hi @suaron, thanks for reporting. Fixed in the commit above.
